name: firekart
description: A new Flutter project.
version: 1.0.0+2
publish_to: none

environment:
  sdk: ">=2.20.0 >3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.0
  #Modules
  domain:
    path: modules/domain
  shared_dependencies:
    path: modules/shared_dependencies
  data:
    path: modules/data
  core:
    path: modules/core
  presentation:
    path: modules/presentation
  notification:
    path: modules/notification
  analytics:
    path: modules/analytics
  deeplink:
    path: modules/deeplink
  assets:
    path: modules/assets

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  dart_code_metrics:
  build_runner: ^2.4.4
  freezed: ^2.3.5
  injectable_generator: ^2.1.6
  auto_route_generator: ^7.1.1
  mockito: ^5.4.1

flutter:
  uses-material-design: true