name: analytics
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_crashlytics: ^3.0.7
  firebase_performance:
  firebase_analytics: ^10.0.7
  shared_dependencies:
    path: ../shared_dependencies
  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  injectable_generator: ^2.1.6
